# This is a basic workflow to help you get started with Actions

name: Build Website

# Controls when the action will run.
on:
  # Allows you to run this workflow manually via an API call
  workflow_dispatch:
    inputs:
      # Front End and Backend URL
      FRONTEND_URL:
        description: "Front End URL"
        required: true
        default: "http://localhost:4200"

      BACKEND_URL:
        description: "Backend End URL"
        required: true
        default: "http://localhost:8080/FreshFoods"

      # MySQL related variables.
      DATABASE_NAME:
        description: "Database Name"
        required: true
        default: "FreshFoods"

      DATABASE_USERNAME:
        description: "MySQL Database Username"
        required: true
        default: "root"

      DATABASE_PASSWORD:
        description: "MySQL Database Password"

      MYSQL_HOST:
        description: "MySQL Service Host"
        required: true
        default: "127.0.0.1"

      MYSQL_PORT:
        description: "MySQL Service Port"
        required: true
        default: "3306"

# Set Inputs as Environment Variables as envsubst requries environment variables
# for substitution.
env:
  MYSQL_HOST: ${{ github.event.inputs.MYSQL_HOST }}
  MYSQL_PORT: ${{ github.event.inputs.MYSQL_PORT }}
  BACKEND_URL: ${{ github.event.inputs.BACKEND_URL }}
  FRONTEND_URL: ${{ github.event.inputs.FRONTEND_URL }}
  DATABASE_NAME: ${{ github.event.inputs.DATABASE_NAME }}
  DATABASE_USERNAME: ${{ github.event.inputs.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ github.event.inputs.DATABASE_PASSWORD }}
  WEB_CONTENT_DIR: "./backend/FreshFoods/WebContent"

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Substitute Environment Variables in a database.sql File
        uses: danielr1996/envsubst-action@1.1.0
        with:
          input: "${{ env.WEB_CONTENT_DIR }}/WEB-INF/database.sql"
          output: "${{ env.WEB_CONTENT_DIR }}/WEB-INF/database.sql"

      - name: Substitute Environment Variables in a content.xml File
        uses: danielr1996/envsubst-action@1.1.0
        with:
          input: "${{ env.WEB_CONTENT_DIR }}/META-INF/context.xml"
          output: "${{ env.WEB_CONTENT_DIR }}/META-INF/context.xml"

      - name: Create env.ts file for the frontend
        run: |
          cat > env.ts << EOF
          export const env = {
            BACKEND_URL: "\${BACKEND_URL}",
            RAVE_API_KEY: "${{ secrets.RAVE_API_KEY }}",
          };
          EOF
          mv env.ts ./src/environments/
          echo "Hello"
          echo $GITHUB_WORKSPACE

      - name: Substitute Environment Variables in a env.ts File
        uses: danielr1996/envsubst-action@1.1.0
        with:
          input: "./src/environments/env.ts"
          output: "./src/environments/env.ts"

      - name: Upload The Backend artifacts
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: ./backend/

      - name: Upload The Frontend artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: |
            .
            !backend/
            !.github/
            !.git/

  # build:
  #   needs: setup
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: dist

  #     - run: |
  #         pwd
  #         ls -la
