# This is a basic workflow to help you get started with Actions

name: Build Website

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually via an API call
  workflow_dispatch:
    inputs:
    
      # Front End and Backend URL
      FRONTEND_URL:
        description: 'Front End URL'
        required: true
        default: 'http://localhost:4200'
      BACKEND_URL:
        description: 'Front End URL'
        required: true
        default: 'http://localhost:4200'
        
      # MySQL related variables.
      DATABASE_NAME:
        description: 'Front End URL'
        required: true
        default: 'http://localhost:4200'
      DATABASE_USERNAME:
        description: 'Front End URL'
        required: true
        default: 'http://localhost:4200'
      DATABASE_PASSWORD:
        description: 'Front End URL'
        required: true
        default: 'http://localhost:4200'

      MYSQL_HOST:
        description: 'Front End URL'
        required: true
        default: 'http://localhost:4200'
      MYSQL_PORT:
        description: 'Front End URL'
        required: true
        default: 'http://localhost:4200'
      
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
